/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from '../../../../build/components/body/scroller.component';
const styles_ScrollerComponent:any[] = ([] as any[]);
export const RenderType_ScrollerComponent:import0.RendererType2 = import0.ɵcrt({
  encapsulation: 2,
  styles: styles_ScrollerComponent,
  data: {}
}
);
export function View_ScrollerComponent_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵted((null as any),['\n    '])),
    import0.ɵncd((null as any),0),
    (l()(),import0.ɵted((null as any),['\n  ']))
  ]
  ,(null as any),(null as any));
}
function View_ScrollerComponent_Host_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
      (l()(),import0.ɵeld(0,(null as any),(null as any),1,'datatable-scroller',[[
        'class',
        'datatable-scroll'
      ]
    ],[
      [
        4,
        'height',
        'px'
      ]
      ,
      [
        4,
        'width',
        'px'
      ]

    ]
    ,(null as any),(null as any),View_ScrollerComponent_0,RenderType_ScrollerComponent)),
    import0.ɵdid(122880,(null as any),0,import1.ScrollerComponent,[
      import0.ElementRef,
      import0.Renderer
    ]
    ,(null as any),(null as any))
  ]
  ,(ck,v) => {
    ck(v,1,0);
  },(ck,v) => {
    const currVal_0:any = import0.ɵnov(v,1).scrollHeight;
    const currVal_1:any = import0.ɵnov(v,1).scrollWidth;
    ck(v,0,0,currVal_0,currVal_1);
  });
}
export const ScrollerComponentNgFactory:import0.ComponentFactory<import1.ScrollerComponent> = import0.ɵccf('datatable-scroller',import1.ScrollerComponent,View_ScrollerComponent_Host_0,{
  scrollbarV: 'scrollbarV',
  scrollbarH: 'scrollbarH',
  scrollHeight: 'scrollHeight',
  scrollWidth: 'scrollWidth'
}
,{scroll: 'scroll'},['*']);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovTG9jYWxEYXRhL3Byb2plY3RzL2FuZ3VsYXIyL25neC1kYXRhdGFibGUvYnVpbGQvY29tcG9uZW50cy9ib2R5L3Njcm9sbGVyLmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9DOi9Mb2NhbERhdGEvcHJvamVjdHMvYW5ndWxhcjIvbmd4LWRhdGF0YWJsZS9idWlsZC9jb21wb25lbnRzL2JvZHkvc2Nyb2xsZXIuY29tcG9uZW50LnRzIiwibmc6Ly8vQzovTG9jYWxEYXRhL3Byb2plY3RzL2FuZ3VsYXIyL25neC1kYXRhdGFibGUvYnVpbGQvY29tcG9uZW50cy9ib2R5L3Njcm9sbGVyLmNvbXBvbmVudC50cy5TY3JvbGxlckNvbXBvbmVudC5odG1sIiwibmc6Ly8vQzovTG9jYWxEYXRhL3Byb2plY3RzL2FuZ3VsYXIyL25neC1kYXRhdGFibGUvYnVpbGQvY29tcG9uZW50cy9ib2R5L3Njcm9sbGVyLmNvbXBvbmVudC50cy5TY3JvbGxlckNvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIlxuICAgIDxuZy1jb250ZW50PjwvbmctY29udGVudD5cbiAgIiwiPGRhdGF0YWJsZS1zY3JvbGxlcj48L2RhdGF0YWJsZS1zY3JvbGxlcj4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7O0lDQUE7Z0JBQ0k7SUFBeUI7Ozs7OztNQ0Q3QjtRQUFBO1FBQUE7TUFBQTtJQUFBO01BQUE7UUFBQTtRQUFBO1FBQUE7TUFBQTs7TUFBQTtRQUFBO1FBQUE7UUFBQTtNQUFBOztJQUFBO0tBQUE7Z0JBQUE7OztJQUFBO0tBQUE7OztJQUFBOztJQUFBO0lBQUE7SUFBQSxTQUFBLG1CQUFBOzs7Ozs7Ozs7In0=
