/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from '../../../../build/components/body/scroller.component';
const styles_ScrollerComponent:any[] = ([] as any[]);
export const RenderType_ScrollerComponent:import0.RendererType2 = import0.ɵcrt({
  encapsulation: 2,
  styles: styles_ScrollerComponent,
  data: {}
}
);
export function View_ScrollerComponent_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵted((null as any),['\n    '])),
    import0.ɵncd((null as any),0),
    (l()(),import0.ɵted((null as any),['\n  ']))
  ]
  ,(null as any),(null as any));
}
function View_ScrollerComponent_Host_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
      (l()(),import0.ɵeld(0,(null as any),(null as any),1,'datatable-scroller',[[
        'class',
        'datatable-scroll'
      ]
    ],[
      [
        4,
        'height',
        'px'
      ]
      ,
      [
        4,
        'width',
        'px'
      ]

    ]
    ,(null as any),(null as any),View_ScrollerComponent_0,RenderType_ScrollerComponent)),
    import0.ɵdid(122880,(null as any),0,import1.ScrollerComponent,[
      import0.ElementRef,
      import0.Renderer
    ]
    ,(null as any),(null as any))
  ]
  ,(ck,v) => {
    ck(v,1,0);
  },(ck,v) => {
    const currVal_0:any = import0.ɵnov(v,1).scrollHeight;
    const currVal_1:any = import0.ɵnov(v,1).scrollWidth;
    ck(v,0,0,currVal_0,currVal_1);
  });
}
export const ScrollerComponentNgFactory:import0.ComponentFactory<import1.ScrollerComponent> = import0.ɵccf('datatable-scroller',import1.ScrollerComponent,View_ScrollerComponent_Host_0,{
  scrollbarV: 'scrollbarV',
  scrollbarH: 'scrollbarH',
  scrollHeight: 'scrollHeight',
  scrollWidth: 'scrollWidth'
}
,{scroll: 'scroll'},['*']);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2F1c3Rpbi9kZXYvbmd4LWRhdGF0YWJsZS9idWlsZC9jb21wb25lbnRzL2JvZHkvc2Nyb2xsZXIuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL1VzZXJzL2F1c3Rpbi9kZXYvbmd4LWRhdGF0YWJsZS9idWlsZC9jb21wb25lbnRzL2JvZHkvc2Nyb2xsZXIuY29tcG9uZW50LnRzIiwibmc6Ly8vVXNlcnMvYXVzdGluL2Rldi9uZ3gtZGF0YXRhYmxlL2J1aWxkL2NvbXBvbmVudHMvYm9keS9zY3JvbGxlci5jb21wb25lbnQudHMuU2Nyb2xsZXJDb21wb25lbnQuaHRtbCIsIm5nOi8vL1VzZXJzL2F1c3Rpbi9kZXYvbmd4LWRhdGF0YWJsZS9idWlsZC9jb21wb25lbnRzL2JvZHkvc2Nyb2xsZXIuY29tcG9uZW50LnRzLlNjcm9sbGVyQ29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiXG4gICAgPG5nLWNvbnRlbnQ+PC9uZy1jb250ZW50PlxuICAiLCI8ZGF0YXRhYmxlLXNjcm9sbGVyPjwvZGF0YXRhYmxlLXNjcm9sbGVyPiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7SUNBQTtnQkFDSTtJQUF5Qjs7Ozs7O01DRDdCO1FBQUE7UUFBQTtNQUFBO0lBQUE7TUFBQTtRQUFBO1FBQUE7UUFBQTtNQUFBOztNQUFBO1FBQUE7UUFBQTtRQUFBO01BQUE7O0lBQUE7S0FBQTtnQkFBQTs7O0lBQUE7S0FBQTs7O0lBQUE7O0lBQUE7SUFBQTtJQUFBLFNBQUEsbUJBQUE7Ozs7Ozs7OzsifQ==
