/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './progress-bar.component';
const styles_ProgressBarComponent:any[] = ([] as any[]);
export const RenderType_ProgressBarComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_ProgressBarComponent,data:{}});
export function View_ProgressBarComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(2,[(_l()(),i0.ɵted(-1,(null as any),['\n    '])),(_l()(),i0.ɵeld(1,
      0,(null as any),(null as any),6,'div',[['class','progress-linear'],['role','progressbar']],
      (null as any),(null as any),(null as any),(null as any),(null as any))),(_l()(),
      i0.ɵted(-1,(null as any),['\n      '])),(_l()(),i0.ɵeld(3,0,(null as any),(null as any),
      3,'div',[['class','container']],(null as any),(null as any),(null as any),(null as any),
      (null as any))),(_l()(),i0.ɵted(-1,(null as any),['\n        '])),(_l()(),i0.ɵeld(5,
      0,(null as any),(null as any),0,'div',[['class','bar']],(null as any),(null as any),
      (null as any),(null as any),(null as any))),(_l()(),i0.ɵted(-1,(null as any),
      ['\n      '])),(_l()(),i0.ɵted(-1,(null as any),['\n    '])),(_l()(),i0.ɵted(-1,
      (null as any),['\n  ']))],(null as any),(null as any));
}
export function View_ProgressBarComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,0,(null as any),(null as any),1,'datatable-progress',
      ([] as any[]),(null as any),(null as any),(null as any),View_ProgressBarComponent_0,
      RenderType_ProgressBarComponent)),i0.ɵdid(1,49152,(null as any),0,i1.ProgressBarComponent,
      ([] as any[]),(null as any),(null as any))],(null as any),(null as any));
}
export const ProgressBarComponentNgFactory:i0.ComponentFactory<i1.ProgressBarComponent> = i0.ɵccf('datatable-progress',
    i1.ProgressBarComponent,View_ProgressBarComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2tqYW5uaXMvRG9jdW1lbnRzL1BlcnNvbmFsL25nLWRhdGF0YWJsZS9zcmMvY29tcG9uZW50cy9ib2R5L3Byb2dyZXNzLWJhci5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vVXNlcnMva2phbm5pcy9Eb2N1bWVudHMvUGVyc29uYWwvbmctZGF0YXRhYmxlL3NyYy9jb21wb25lbnRzL2JvZHkvcHJvZ3Jlc3MtYmFyLmNvbXBvbmVudC50cyIsIm5nOi8vL1VzZXJzL2tqYW5uaXMvRG9jdW1lbnRzL1BlcnNvbmFsL25nLWRhdGF0YWJsZS9zcmMvY29tcG9uZW50cy9ib2R5L3Byb2dyZXNzLWJhci5jb21wb25lbnQudHMuUHJvZ3Jlc3NCYXJDb21wb25lbnQuaHRtbCIsIm5nOi8vL1VzZXJzL2tqYW5uaXMvRG9jdW1lbnRzL1BlcnNvbmFsL25nLWRhdGF0YWJsZS9zcmMvY29tcG9uZW50cy9ib2R5L3Byb2dyZXNzLWJhci5jb21wb25lbnQudHMuUHJvZ3Jlc3NCYXJDb21wb25lbnRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCJcbiAgICA8ZGl2IGNsYXNzPVwicHJvZ3Jlc3MtbGluZWFyXCIgcm9sZT1cInByb2dyZXNzYmFyXCI+XG4gICAgICA8ZGl2IGNsYXNzPVwiY29udGFpbmVyXCI+XG4gICAgICAgIDxkaXYgY2xhc3M9XCJiYXJcIj48L2Rpdj5cbiAgICAgIDwvZGl2PlxuICAgIDwvZGl2PlxuICAiLCI8ZGF0YXRhYmxlLXByb2dyZXNzPjwvZGF0YXRhYmxlLXByb2dyZXNzPiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7O29CQ0FBLDhDQUNJO01BQUE7TUFBQSx3RUFBZ0Q7YUFBQSxpQ0FDOUM7TUFBQTtNQUFBLGdCQUF1QixrREFDckI7TUFBQTtNQUFBLDRDQUF1QjtNQUFBLGVBQ25CLDhDQUNGO01BQUE7OztvQkNMVjtNQUFBO3FDQUFBLFVBQUE7TUFBQTs7OyJ9
