/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '../../../src/components/row-detail.directive';
import * as import1 from '@angular/core/src/linker/view';
export class Wrapper_DatatableRowDetailDirective {
  context:import0.DatatableRowDetailDirective;
  changed:boolean;
  constructor() {
    this.changed = false;
    this.context = new import0.DatatableRowDetailDirective();
  }
  detectChangesInInputProps(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    return changed;
  }
  detectChangesInHostProps(view:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
}