/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core';
import * as import1 from '@angular/common';
import * as import2 from '../../../../build/components/footer/footer.component';
import * as import3 from './pager.component.ngfactory';
import * as import4 from '../../../../build/components/footer/pager.component';
const styles_DataTableFooterComponent:any[] = ([] as any[]);
export const RenderType_DataTableFooterComponent:import0.RendererTypeV2 = import0.ɵcrt({
  encapsulation: 2,
  styles: styles_DataTableFooterComponent,
  data: {}
}
);
function View_DataTableFooterComponent_1():import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    import0.ɵeld(0,(null as any),(null as any),1,'span',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any)),
    import0.ɵted((null as any),[
      '\n          ',
      ' ',
      ' / \n        '
    ]
    )
  ]
  ,(null as any),(check,view) => {
    var comp:any = view.component;
    const currVal_0:any = comp.selectedCount.toLocaleString();
    const currVal_1:any = comp.selectedMessage;
    check(view,1,0,currVal_0,currVal_1);
  });
}
export function View_DataTableFooterComponent_0():import0.ɵViewDefinition {
  return import0.ɵvid(2,[
    import0.ɵted((null as any),['\n    ']),
      import0.ɵeld(0,(null as any),(null as any),13,'div',([] as any[]),[[
        2,
        'height',
        'px'
      ]
    ],(null as any),(null as any),(null as any),(null as any)),
    import0.ɵdid(139264,(null as any),0,import1.NgClass,[
      import0.IterableDiffers,
      import0.KeyValueDiffers,
      import0.ElementRef,
      import0.Renderer
    ]
      ,{ngClass: [
        0,
        'ngClass'
      ]
    },(null as any)),
    import0.ɵpod(['selected-count']),
    import0.ɵted((null as any),['\n      ']),
      import0.ɵeld(0,(null as any),(null as any),4,'div',[[
        'class',
        'page-count'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any)),
    import0.ɵted((null as any),['\n        ']),
    import0.ɵand(8388608,(null as any),(null as any),1,(null as any),View_DataTableFooterComponent_1),
    import0.ɵdid(8192,(null as any),0,import1.NgIf,[
      import0.ViewContainerRef,
      import0.TemplateRef
    ]
      ,{ngIf: [
        0,
        'ngIf'
      ]
    },(null as any)),
    import0.ɵted((null as any),[
      '\n\n        ',
      ' ',
      '\n      '
    ]
    ),
    import0.ɵted((null as any),['\n      ']),
      import0.ɵeld(0,(null as any),(null as any),2,'datatable-pager',[[
        'class',
        'datatable-pager'
      ]
      ],[[
        3,
        'hidden',
        0
      ]
      ],[[
        (null as any),
        'change'
      ]
    ],(view,eventName,$event) => {
      var allowDefault:boolean = true;
      var comp:import2.DataTableFooterComponent = view.component;
      if (('change' === eventName)) {
        const pd_0:any = ((<any>comp.page.emit($event)) !== false);
        allowDefault = (pd_0 && allowDefault);
      }
      return allowDefault;
    },import3.View_DataTablePagerComponent_0,import3.RenderType_DataTablePagerComponent),
    import0.ɵdid(24576,(null as any),0,import4.DataTablePagerComponent,([] as any[]),{
      pagerLeftArrowIcon: [
        0,
        'pagerLeftArrowIcon'
      ]
      ,
      pagerRightArrowIcon: [
        1,
        'pagerRightArrowIcon'
      ]
      ,
      pagerPreviousIcon: [
        2,
        'pagerPreviousIcon'
      ]
      ,
      pagerNextIcon: [
        3,
        'pagerNextIcon'
      ]
      ,
      size: [
        4,
        'size'
      ]
      ,
      count: [
        5,
        'count'
      ]
      ,
      page: [
        6,
        'page'
      ]

    }
    ,{change: 'change'}),
    import0.ɵted((null as any),['\n      ']),
    import0.ɵted((null as any),['\n    ']),
    import0.ɵted((null as any),['\n  '])
  ]
  ,(check,view) => {
    var comp:import2.DataTableFooterComponent = view.component;
    const currVal_0:any = check(view,3,0,comp.selectedMessage);
    check(view,2,0,currVal_0);
    const currVal_1:any = comp.selectedMessage;
    check(view,8,0,currVal_1);
    const currVal_2:any = comp.pagerLeftArrowIcon;
    const currVal_3:any = comp.pagerRightArrowIcon;
    const currVal_4:any = comp.pagerPreviousIcon;
    const currVal_5:any = comp.pagerNextIcon;
    const currVal_6:any = comp.pageSize;
    const currVal_7:any = comp.rowCount;
    const currVal_8:any = comp.curPage;
    check(view,12,0,currVal_2,currVal_3,currVal_4,currVal_5,currVal_6,currVal_7,currVal_8);
  },(check,view) => {
    var comp:import2.DataTableFooterComponent = view.component;
    const currVal_0:any = comp.footerHeight;
    check(view,1,0,currVal_0);
    const currVal_1:any = comp.rowCount.toLocaleString();
    const currVal_2:any = comp.totalMessage;
    check(view,9,0,currVal_1,currVal_2);
    const currVal_3:boolean = !comp.isVisible;
    check(view,11,0,currVal_3);
  });
}
const RenderType_DataTableFooterComponent_Host:import0.RendererTypeV2 = import0.ɵcrt({
  encapsulation: 2,
  styles: ([] as any[]),
  data: {}
}
);
function View_DataTableFooterComponent_Host_0():import0.ɵViewDefinition {
  return import0.ɵvid(0,[
      import0.ɵeld(0,(null as any),(null as any),1,'datatable-footer',[[
        'class',
        'datatable-footer'
      ]
    ],(null as any),(null as any),(null as any),View_DataTableFooterComponent_0,RenderType_DataTableFooterComponent),
    import0.ɵdid(24576,(null as any),0,import2.DataTableFooterComponent,([] as any[]),(null as any),(null as any))
  ]
  ,(null as any),(null as any));
}
export const DataTableFooterComponentNgFactory:import0.ComponentFactory<import2.DataTableFooterComponent> = import0.ɵccf('datatable-footer',import2.DataTableFooterComponent,View_DataTableFooterComponent_Host_0);