/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core';
import * as import1 from '../../../../build/components/footer/pager.component';
import * as import2 from '@angular/common';
const styles_DataTablePagerComponent:any[] = ([] as any[]);
export const RenderType_DataTablePagerComponent:import0.RendererTypeV2 = import0.ɵcrt({
  encapsulation: 2,
  styles: styles_DataTablePagerComponent,
  data: {}
}
);
function View_DataTablePagerComponent_1():import0.ɵViewDefinition {
  return import0.ɵvid(0,[
      import0.ɵeld(0,(null as any),(null as any),4,'li',[[
        'class',
        'pages'
      ]
      ],[[
        1,
        'active'
      ]
    ],(null as any),(null as any),(null as any),(null as any)),
    import0.ɵted((null as any),['\n        ']),
      import0.ɵeld(0,(null as any),(null as any),1,'a',[[
        'href',
        'javascript:void(0)'
      ]
      ],(null as any),[[
        (null as any),
        'click'
      ]
    ],(view,eventName,$event) => {
      var allowDefault:boolean = true;
      var comp:any = view.component;
      if (('click' === eventName)) {
        const pd_0:any = ((<any>comp.selectPage(view.context.$implicit.number)) !== false);
        allowDefault = (pd_0 && allowDefault);
      }
      return allowDefault;
    },(null as any),(null as any)),
    import0.ɵted((null as any),[
      '\n          ',
      '\n        '
    ]
    ),
    import0.ɵted((null as any),['\n      '])
  ]
  ,(null as any),(check,view) => {
    var comp:any = view.component;
    const currVal_0:any = (view.context.$implicit.number === comp.page);
    check(view,0,0,currVal_0);
    const currVal_1:any = view.context.$implicit.text;
    check(view,3,0,currVal_1);
  });
}
export function View_DataTablePagerComponent_0():import0.ɵViewDefinition {
  return import0.ɵvid(2,[
    import0.ɵted((null as any),['\n    ']),
      import0.ɵeld(0,(null as any),(null as any),36,'ul',[[
        'class',
        'pager'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any)),
    import0.ɵted((null as any),['\n      ']),
      import0.ɵeld(0,(null as any),(null as any),6,'li',([] as any[]),[[
        1,
        'disabled'
      ]
    ],(null as any),(null as any),(null as any),(null as any)),
    import0.ɵted((null as any),['\n        ']),
      import0.ɵeld(0,(null as any),(null as any),3,'a',[[
        'href',
        'javascript:void(0)'
      ]
      ],(null as any),[[
        (null as any),
        'click'
      ]
    ],(view,eventName,$event) => {
      var allowDefault:boolean = true;
      var comp:import1.DataTablePagerComponent = view.component;
      if (('click' === eventName)) {
        const pd_0:any = ((<any>comp.selectPage(1)) !== false);
        allowDefault = (pd_0 && allowDefault);
      }
      return allowDefault;
    },(null as any),(null as any)),
    import0.ɵted((null as any),['\n          ']),
      import0.ɵeld(0,(null as any),(null as any),0,'i',([] as any[]),[[
        3,
        'className',
        0
      ]
    ],(null as any),(null as any),(null as any),(null as any)),
    import0.ɵted((null as any),['\n        ']),
    import0.ɵted((null as any),['\n      ']),
    import0.ɵted((null as any),['\n      ']),
      import0.ɵeld(0,(null as any),(null as any),6,'li',([] as any[]),[[
        1,
        'disabled'
      ]
    ],(null as any),(null as any),(null as any),(null as any)),
    import0.ɵted((null as any),['\n        ']),
      import0.ɵeld(0,(null as any),(null as any),3,'a',[[
        'href',
        'javascript:void(0)'
      ]
      ],(null as any),[[
        (null as any),
        'click'
      ]
    ],(view,eventName,$event) => {
      var allowDefault:boolean = true;
      var comp:import1.DataTablePagerComponent = view.component;
      if (('click' === eventName)) {
        const pd_0:any = ((<any>comp.prevPage()) !== false);
        allowDefault = (pd_0 && allowDefault);
      }
      return allowDefault;
    },(null as any),(null as any)),
    import0.ɵted((null as any),['\n          ']),
      import0.ɵeld(0,(null as any),(null as any),0,'i',([] as any[]),[[
        3,
        'className',
        0
      ]
    ],(null as any),(null as any),(null as any),(null as any)),
    import0.ɵted((null as any),['\n        ']),
    import0.ɵted((null as any),['\n      ']),
    import0.ɵted((null as any),['\n      ']),
    import0.ɵand(8388608,(null as any),(null as any),1,(null as any),View_DataTablePagerComponent_1),
    import0.ɵdid(401408,(null as any),0,import2.NgForOf,[
      import0.ViewContainerRef,
      import0.TemplateRef,
      import0.IterableDiffers
    ]
      ,{ngForOf: [
        0,
        'ngForOf'
      ]
    },(null as any)),
    import0.ɵted((null as any),['\n      ']),
      import0.ɵeld(0,(null as any),(null as any),6,'li',([] as any[]),[[
        1,
        'disabled'
      ]
    ],(null as any),(null as any),(null as any),(null as any)),
    import0.ɵted((null as any),['\n        ']),
      import0.ɵeld(0,(null as any),(null as any),3,'a',[[
        'href',
        'javascript:void(0)'
      ]
      ],(null as any),[[
        (null as any),
        'click'
      ]
    ],(view,eventName,$event) => {
      var allowDefault:boolean = true;
      var comp:import1.DataTablePagerComponent = view.component;
      if (('click' === eventName)) {
        const pd_0:any = ((<any>comp.nextPage()) !== false);
        allowDefault = (pd_0 && allowDefault);
      }
      return allowDefault;
    },(null as any),(null as any)),
    import0.ɵted((null as any),['\n          ']),
      import0.ɵeld(0,(null as any),(null as any),0,'i',([] as any[]),[[
        3,
        'className',
        0
      ]
    ],(null as any),(null as any),(null as any),(null as any)),
    import0.ɵted((null as any),['\n        ']),
    import0.ɵted((null as any),['\n      ']),
    import0.ɵted((null as any),['\n      ']),
      import0.ɵeld(0,(null as any),(null as any),6,'li',([] as any[]),[[
        1,
        'disabled'
      ]
    ],(null as any),(null as any),(null as any),(null as any)),
    import0.ɵted((null as any),['\n        ']),
      import0.ɵeld(0,(null as any),(null as any),3,'a',[[
        'href',
        'javascript:void(0)'
      ]
      ],(null as any),[[
        (null as any),
        'click'
      ]
    ],(view,eventName,$event) => {
      var allowDefault:boolean = true;
      var comp:import1.DataTablePagerComponent = view.component;
      if (('click' === eventName)) {
        const pd_0:any = ((<any>comp.selectPage(comp.totalPages)) !== false);
        allowDefault = (pd_0 && allowDefault);
      }
      return allowDefault;
    },(null as any),(null as any)),
    import0.ɵted((null as any),['\n          ']),
      import0.ɵeld(0,(null as any),(null as any),0,'i',([] as any[]),[[
        3,
        'className',
        0
      ]
    ],(null as any),(null as any),(null as any),(null as any)),
    import0.ɵted((null as any),['\n        ']),
    import0.ɵted((null as any),['\n      ']),
    import0.ɵted((null as any),['\n    ']),
    import0.ɵted((null as any),['\n  '])
  ]
  ,(check,view) => {
    var comp:import1.DataTablePagerComponent = view.component;
    const currVal_0:any = comp.pages;
    check(view,20,0,currVal_0);
  },(check,view) => {
    var comp:import1.DataTablePagerComponent = view.component;
    const currVal_0:boolean = !comp.canPrevious();
    check(view,3,0,currVal_0);
    const currVal_1:any = import0.ɵinlineInterpolate(1,'',comp.pagerPreviousIcon,'');
    check(view,7,0,currVal_1);
    const currVal_2:boolean = !comp.canPrevious();
    check(view,11,0,currVal_2);
    const currVal_3:any = import0.ɵinlineInterpolate(1,'',comp.pagerLeftArrowIcon,'');
    check(view,15,0,currVal_3);
    const currVal_4:boolean = !comp.canNext();
    check(view,22,0,currVal_4);
    const currVal_5:any = import0.ɵinlineInterpolate(1,'',comp.pagerRightArrowIcon,'');
    check(view,26,0,currVal_5);
    const currVal_6:boolean = !comp.canNext();
    check(view,30,0,currVal_6);
    const currVal_7:any = import0.ɵinlineInterpolate(1,'',comp.pagerNextIcon,'');
    check(view,34,0,currVal_7);
  });
}
const RenderType_DataTablePagerComponent_Host:import0.RendererTypeV2 = import0.ɵcrt({
  encapsulation: 2,
  styles: ([] as any[]),
  data: {}
}
);
function View_DataTablePagerComponent_Host_0():import0.ɵViewDefinition {
  return import0.ɵvid(0,[
      import0.ɵeld(0,(null as any),(null as any),1,'datatable-pager',[[
        'class',
        'datatable-pager'
      ]
    ],(null as any),(null as any),(null as any),View_DataTablePagerComponent_0,RenderType_DataTablePagerComponent),
    import0.ɵdid(24576,(null as any),0,import1.DataTablePagerComponent,([] as any[]),(null as any),(null as any))
  ]
  ,(null as any),(null as any));
}
export const DataTablePagerComponentNgFactory:import0.ComponentFactory<import1.DataTablePagerComponent> = import0.ɵccf('datatable-pager',import1.DataTablePagerComponent,View_DataTablePagerComponent_Host_0);