/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './datatable.module';
import * as i2 from '@angular/common';
import * as i3 from './services/scrollbar-helper.service';
import * as i4 from '@angular/platform-browser';
export const NgxDatatableModuleNgFactory:i0.NgModuleFactory<i1.NgxDatatableModule> = i0.ɵcmf(i1.NgxDatatableModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,([] as any[])],[3,i0.ComponentFactoryResolver],i0.NgModuleRef]),i0.ɵmpd(4608,
          i2.NgLocalization,i2.NgLocaleLocalization,[i0.LOCALE_ID]),i0.ɵmpd(4608,i3.ScrollbarHelper,
          i3.ScrollbarHelper,[i4.DOCUMENT]),i0.ɵmpd(512,i2.CommonModule,i2.CommonModule,
          ([] as any[])),i0.ɵmpd(512,i1.NgxDatatableModule,i1.NgxDatatableModule,([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2tqYW5uaXMvRG9jdW1lbnRzL1BlcnNvbmFsL25nLWRhdGF0YWJsZS9zcmMvZGF0YXRhYmxlLm1vZHVsZS5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9Vc2Vycy9ramFubmlzL0RvY3VtZW50cy9QZXJzb25hbC9uZy1kYXRhdGFibGUvc3JjL2RhdGF0YWJsZS5tb2R1bGUudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OyJ9
